import type { Agent, ModelCatalog, Note, VaultGraph, ProjectInfo, RuntimeEvent, RuntimeSnapshot, Status, Workspace } from '../types';
import { PixelIcon } from '../components/PixelIcon';
import { Button } from '../components/UI';
import { AgentCards } from '../components/AgentCards';
import { RuntimeCore } from '../components/RuntimeCore';
import { SystemStrip } from '../components/SystemStrip';
import type { ModuleName } from '../components/ModulePanels';
export type MissionMode = 'mission' | 'chat' | 'plan' | 'build';
type BaseProps = { workspace: Workspace; status: Status; runtime: RuntimeSnapshot | null; history: RuntimeSnapshot[]; runtimeEvents: RuntimeEvent[]; connected: boolean; runtimeError: string; notes: Note[]; agent: Agent; selectAgent: (agent: Agent) => void; draft: string; setDraft: (text: string) => void; mode: MissionMode; setMode: (mode: MissionMode) => void; pending: Record<string, string>; mission: { id: string; task: string; phase: string } | null; project: ProjectInfo | null; contexts: string[]; launch: () => void; stop: () => void; start: (agent: Agent) => void; openAgent: (agent: Agent) => void; attach: (path: string) => void; settings: () => void; checkConnections: () => void; openModule: (module: ModuleName) => void; automationCount: number | null; retryRuntime: () => void };
type Props = BaseProps & { catalog: ModelCatalog | null; preferencesBusy: boolean; changePreferences: (agent: Agent, model: string, effort: string) => void; drafts: Record<Agent, string>; setAgentDraft: (agent: Agent, text: string) => void; submitAgent: (agent: Agent, mode: 'chat' | 'plan' | 'build') => void; stopAgent: (agent: Agent) => void; saveAgentResponse: (agent: Agent, text: string) => void; graph: VaultGraph | null; toggleContext: (path: string) => void };
export function Home(p: Props) {
  const activeId = p.workspace.active[p.agent], running = p.mode === 'mission' ? !!p.mission : !!(activeId && p.pending[activeId]);
  const terminal = p.runtimeEvents.find(event => event.type === 'terminal' && event.text)?.text;
  return <>
    <SystemStrip runtime={p.runtime} history={p.history} connected={p.connected} />
    <div className="cockpit-agents"><AgentCards catalog={p.catalog} preferencesBusy={p.preferencesBusy} changePreferences={p.changePreferences} drafts={p.drafts} setDraft={p.setAgentDraft} submit={p.submitAgent} stop={p.stopAgent} saveResponse={p.saveAgentResponse} contextCount={p.contexts.length} workspace={p.workspace} status={p.status} runtime={p.runtime} mission={p.mission} agent={p.agent} pending={p.pending} select={p.selectAgent} open={p.openAgent} start={p.start} settings={p.settings} check={p.checkConnections} /><button className="mission-history-link" onClick={() => p.openModule('missions')}><PixelIcon name="chat" size={12} />{p.workspace.sessions.length} SAVED SESSIONS<span>MISSION HISTORY ↗</span></button></div>
    <div className="cockpit-core"><RuntimeCore graph={p.graph} contexts={p.contexts} toggleContext={p.toggleContext} working={{ claude: Object.keys(p.pending).some(id => p.workspace.sessions.find(session => session.id === id)?.agent === "claude") && (!p.mission || p.mission.phase === "planning"), codex: Object.keys(p.pending).some(id => p.workspace.sessions.find(session => session.id === id)?.agent === "codex") && (!p.mission || p.mission.phase === "building") }} runtime={p.runtime} events={p.runtimeEvents} connected={p.connected} phase={p.mission?.phase} /><div className="system-modules" role="group" aria-label="Local engine modules"><button className="reference-panel module-tile" aria-label="Projects" onClick={() => p.openModule('projects')}><div><PixelIcon name="folder" size={22} /><h2>PROJECTS</h2></div><strong>{p.project?.name || 'CONNECT PROJECT'}</strong><span>{p.project ? `${p.project.branch || 'Local folder'}${p.project.dirty ? ' · changes' : ''}` : 'Select a folder or create one'}</span><i>OPEN ↗</i></button><button className="reference-panel module-tile" aria-label="Automations" onClick={() => p.openModule('automations')}><div><PixelIcon name="settings" size={22} /><h2>AUTOMATIONS</h2></div><strong>{p.automationCount === null ? 'READING ENGINE' : `${p.automationCount} LOCAL ACTIONS`}</strong><span>Tests · builds · vault tools</span><i>OPEN ↗</i></button><button className="reference-panel module-tile" aria-label="Files" onClick={() => p.openModule('files')}><div><PixelIcon name="folder" size={22} /><h2>FILES</h2></div><strong>{p.project ? 'PROJECT SOURCE' : 'NO PROJECT YET'}</strong><span>Browse real files and folders</span><i>OPEN ↗</i></button><button className="reference-panel module-tile terminal-tile" aria-label="Terminal" onClick={() => p.openModule('terminal')}><div><PixelIcon name="terminal" size={22} /><h2>TERMINAL</h2></div><strong>{p.connected ? 'LOCAL ENGINE' : 'CONNECTING'}</strong><span>{terminal?.trim().slice(0, 90) || 'Run status, test, or build'}</span><i>OPEN ↗</i></button></div>{p.runtimeError && <div className="runtime-connection-error"><p>{p.runtimeError}</p><button onClick={p.retryRuntime}>Retry engine ↗</button></div>}</div>
    <section className="reference-panel cockpit-mission" aria-label="Mission Control"><form className="cockpit-mission-form" onSubmit={event => { event.preventDefault(); if (!running) p.launch(); }}><PixelIcon name="terminal" size={24} /><textarea rows={1} aria-label="Your prompt" placeholder={p.mode === 'mission' ? 'What should we build today?' : `Message ${p.agent === 'claude' ? 'Claude' : 'Codex'}...`} value={p.draft} maxLength={20000} onChange={event => p.setDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing) { event.preventDefault(); if (!running) p.launch(); } }} />{running ? <Button variant="danger" icon="stop" onClick={p.stop} aria-label="Stop mission">STOP</Button> : <Button variant="green" icon="play" type="submit" aria-label="Launch mission" disabled={!p.draft.trim()}>LAUNCH</Button>}</form><div className="cockpit-mission-options"><select aria-label="Mission mode" value={p.mode} onChange={event => p.setMode(event.target.value as MissionMode)} disabled={!!p.mission}><option value="mission">Mission · Claude plans → Codex builds</option><option value="chat">Chat · {p.agent === 'claude' ? 'Claude' : 'Codex'}</option><option value="plan">Claude · project plan</option><option value="build">Codex · project build</option></select><div><PixelIcon name="book" size={11} /><select aria-label="Attach a note" value="" onChange={event => p.attach(event.target.value)}><option value="">{p.contexts.length ? `${p.contexts.length} context files selected` : 'Attach vault context'}</option>{p.notes.map(note => <option key={note.path} value={note.path}>{note.title}</option>)}</select></div><span>{p.mission ? p.mission.phase.toUpperCase() : p.mode === 'mission' ? p.project ? `PROJECT / ${p.project.name}` : 'CONNECT A PROJECT TO BUILD' : `SUBSCRIPTION / ${p.agent.toUpperCase()}`}</span></div></section>
  </>;
}
