import { useEffect, useRef } from 'react';
import type { Agent, Note, Session, Status } from '../types';
import { Badge, Button } from '../components/UI';
import { PixelIcon } from '../components/PixelIcon';
import { Markdown } from '../components/Markdown';

type Props = { agent: Agent; active?: boolean; setAgent: (agent: Agent) => void; sessions: Session[]; current?: Session; draft: string; setDraft: (draft: string) => void; status: Status; notes: Note[]; pending: boolean; send: () => void; stop: () => void; start: () => void; openSession: (id: string) => void; save: (text: string) => void; attach: (path: string) => void; settings: () => void };
export function Workbench(p: Props) {
  const messages = useRef<HTMLDivElement>(null);
  useEffect(() => { if (p.active !== false && messages.current) messages.current.scrollTop = messages.current.scrollHeight; }, [p.current?.messages, p.current?.id, p.agent, p.active]);
  const name = p.agent === 'claude' ? 'Claude' : 'Codex';
  const sessions = p.sessions.filter(s => s.agent === p.agent);
  const connected = p.status.connected[p.agent];
  return <div className="workbench-page">
    <div className="module-heading"><div><span className="module-number">01</span><PixelIcon name="terminal" size={15} /><h2>Agent workbench</h2></div><span className="module-tag">THINK / BUILD</span></div>
    <div className="workbench-shell panel"><div className="chat-area">
      <div className="chat-top"><div className="agent-tabs" aria-label="Choose an agent">{(['claude', 'codex'] as Agent[]).map(agent => <button key={agent} className={p.agent === agent ? `active ${agent}` : ''} aria-pressed={p.agent === agent} onClick={() => p.setAgent(agent)}><PixelIcon name={agent === 'claude' ? 'spark' : 'terminal'} size={16} />{agent === 'claude' ? 'Claude' : 'Codex'}</button>)}</div><span className="agent-connection"><i className={`status-dot ${connected ? '' : 'idle'}`} /><span>{connected ? 'SUBSCRIPTION' : 'SIGN IN'}</span></span><span className="model-label">{p.status.models[p.agent] === 'auto' ? 'AUTO MODEL' : p.status.models[p.agent]}</span></div>
      <div className="session-strip"><PixelIcon name="chat" size={11} /><select aria-label={`${name} sessions`} value={p.current?.id || ''} onChange={e => p.openSession(e.target.value)}><option value="" disabled>{sessions.length ? 'Choose a session' : 'Fresh conversation'}</option>{sessions.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</select><Button icon="plus" variant="ghost" aria-label={`New ${name} session`} onClick={p.start}>New</Button></div>
      <div ref={messages} className="chat-messages" aria-live="polite" aria-busy={p.pending}>{!p.current?.messages.length ? <div className="chat-empty"><div className={`large-item-slot ${p.agent}`}><PixelIcon name={p.agent === 'claude' ? 'spark' : 'terminal'} size={32} /><span /><span /></div><div className="eyebrow">{p.agent === 'claude' ? 'REASONING ENGINE' : 'BUILD ENGINE'}</div><h2>{p.agent === 'claude' ? 'A thought becomes a trajectory.' : 'Your next idea. Executable.'}</h2><p>{p.agent === 'claude' ? 'Make a plan, explore an idea, or think through the next move.' : 'Build, debug, and move from a good plan to working code.'}</p><div className="prompt-chips">{(p.agent === 'claude' ? ['Plan my next project', 'Explore an idea', 'Explain a concept'] : ['Build a small app', 'Review my code', 'Implement a plan']).map(prompt => <button key={prompt} onClick={() => p.setDraft(prompt)}>{prompt}<span>↗</span></button>)}</div></div> : p.current.messages.map(message => <article className={`message ${message.role} ${message.error ? 'error' : ''}`} key={message.id}><div className="message-avatar"><PixelIcon name={message.role === 'user' ? 'cube' : p.agent === 'claude' ? 'spark' : 'terminal'} size={14} /></div><div className="message-body"><div className="message-heading"><strong>{message.role === 'user' ? 'YOU' : name.toUpperCase()}</strong>{message.demo && <Badge tone="gold">ARCHIVED</Badge>}{message.pending && <span className="thinking">TRANSMITTING<span>...</span></span>}</div>{message.role === 'user' ? <p className="user-message-text">{message.content}</p> : message.content ? <Markdown>{message.content}</Markdown> : <div className="loading-blocks"><i /><i /><i /></div>}{message.role === 'assistant' && !message.pending && !message.error && <div className="message-actions"><Button icon="copy" variant="ghost" onClick={() => void navigator.clipboard.writeText(message.content)}>Copy</Button><Button icon="save" variant="ghost" onClick={() => p.save(message.content)}>Save to vault</Button></div>}</div></article>)}</div>
      {!connected && <div className="demo-strip"><PixelIcon name="link" size={11} /><span>Connect your {name} subscription to begin.</span><button onClick={p.settings}>Sign in ↗</button></div>}
      <form className="composer" onSubmit={e => { e.preventDefault(); p.send(); }}><textarea aria-label="Your prompt" placeholder={`Message ${name}...`} value={p.draft} maxLength={20000} rows={2} onChange={e => p.setDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); if (!p.pending) p.send(); } }} /><div className="composer-footer"><div className="composer-tools"><PixelIcon name="book" size={13} /><select aria-label="Attach a note" value="" onChange={e => p.attach(e.target.value)}><option value="">Attach vault note</option>{p.notes.map(note => <option key={note.path} value={note.path}>{note.title}</option>)}</select><span className="keyboard-hint">↵ SEND</span></div>{p.pending ? <Button icon="stop" variant="danger" onClick={p.stop}>Stop</Button> : <Button type="submit" variant="green" icon="arrow" aria-label="Send message" disabled={!p.draft.trim()}>Send</Button>}</div></form>
    </div></div>
  </div>;
}
