import { useEffect, useState } from 'react';
import type { ProjectInfo, Status } from '../types';
import { Badge, Button, SectionHeading } from '../components/UI';
import { PixelIcon } from '../components/PixelIcon';
type Props = { status: Status; project: ProjectInfo | null; mission: { id: string; task: string; phase: string } | null; launch: (task: string) => void; stop: () => void; openProjects: () => void };
export function Workflows(p: Props) {
  const [task, setTask] = useState(() => localStorage.getItem('aphelion.workflow-task.v1') || '');
  useEffect(() => { try { localStorage.setItem('aphelion.workflow-task.v1', task); } catch { /* Conversations and receipts retain completed work. */ } }, [task]);
  return <div className="workflows-page page-content"><div className="page-intro"><div><div className="eyebrow">REAL MISSION ORCHESTRATION</div><h1>Plan. Build. Remember.</h1><p>Claude reads the project context. Codex writes the implementation. Your vault keeps the receipt.</p></div><Badge tone="green">SUBSCRIPTION AGENTS</Badge></div><div className="workflow-grid"><section className="panel recipe-panel"><SectionHeading eyebrow="LOCAL ENGINE" title="One connected mission" /><p className="recipe-description">Each stage runs against your selected working directory, using the Markdown notes you attach as context.</p>{([{ icon: 'spark', title: 'Claude plans', text: 'Read context and make a practical implementation plan.', phase: 'planning' }, { icon: 'terminal', title: 'Codex builds', text: 'Implement the plan in the connected project files.', phase: 'building' }, { icon: 'book', title: 'Obsidian remembers', text: 'Save the plan, build output, and project receipt.', phase: 'saving' }] as const).map(step => <div className="recipe-step" key={step.phase}><div className="item-slot"><PixelIcon name={step.icon} size={22} /></div><div><span>{step.phase.toUpperCase()}</span><h3>{step.title}</h3><p>{step.text}</p></div><Badge tone={p.mission?.phase === step.phase ? 'green' : 'muted'}>{p.mission?.phase === step.phase ? 'RUNNING' : 'READY'}</Badge></div>)}<div className="recipe-note"><PixelIcon name="folder" size={16} /><span>{p.project ? `${p.project.name}\n${p.project.path}` : 'Connect or create a real project directory to begin.'}</span></div><Button icon="folder" onClick={p.openProjects}>{p.project ? 'Manage project' : 'Connect project'}</Button></section><section className="panel task-panel"><SectionHeading eyebrow="MISSION INPUT" title="What should we build?" /><label className="sr-only" htmlFor="workflow-task">Workflow task</label><textarea id="workflow-task" value={task} maxLength={20000} onChange={event => setTask(event.target.value)} disabled={!!p.mission} placeholder="Describe the working result you want in your project." rows={7} /><div className="workflow-live-info"><span className="status-dot" />{p.mission ? `Mission ${p.mission.phase}` : p.status.connected.claude && p.status.connected.codex ? 'Both subscription agents connected' : 'Connect both subscription agents in Settings'}</div><div className="task-actions"><span>{p.mission ? 'Partial replies remain in the agent sessions.' : 'The launcher will open the live command center.'}</span>{p.mission ? <Button variant="danger" icon="stop" onClick={p.stop}>Stop workflow</Button> : <Button variant="green" icon="play" onClick={() => p.launch(task)} disabled={!task.trim()}>Run workflow</Button>}</div></section></div></div>;
}
