import { useState } from 'react';
import type { Agent, ModelCatalog, RuntimeSnapshot, Status, Workspace } from '../types';
import { MinecraftWorker } from './MinecraftWorker';
import { PixelIcon } from './PixelIcon';
import { Button } from './UI';
import { Markdown } from './Markdown';
import { AgentPreferences, effortChoices } from './AgentPreferences';
type Props = { workspace: Workspace; status: Status; catalog: ModelCatalog | null; preferencesBusy: boolean; changePreferences: (agent: Agent, model: string, effort: string) => void; runtime?: RuntimeSnapshot | null; mission?: { id: string; task: string; phase: string } | null; agent: Agent; pending: Record<string, string>; drafts: Record<Agent, string>; setDraft: (agent: Agent, text: string) => void; submit: (agent: Agent, mode: 'chat' | 'plan' | 'build') => void; stop: (agent: Agent) => void; saveResponse: (agent: Agent, text: string) => void; contextCount: number; select: (agent: Agent) => void; open: (agent: Agent) => void; start: (agent: Agent) => void; settings: () => void; check: () => void };
export function AgentCards(p: Props) {
  const [modes, setModes] = useState<Record<Agent, 'chat' | 'plan' | 'build'>>({ claude: 'chat', codex: 'chat' });
  return <div className="agent-card-grid">{(['claude', 'codex'] as const).map(agent => {
    const name = agent === 'claude' ? 'Claude' : 'Codex', sessions = p.workspace.sessions.filter(s => s.agent === agent);
    const running = sessions.find(s => !!p.pending[s.id]), current = running || sessions.find(s => s.id === p.workspace.active[agent]);
    const connected = p.status.connected[agent], checking = p.status.auth[agent].detail.startsWith('Checking');
    const inMission = !!p.mission && current?.title === p.mission.task.slice(0, 48), waiting = inMission && agent === 'codex' && p.mission?.phase === 'planning';
    const phase = checking ? 'CHECKING' : running ? waiting ? 'WAITING' : p.mission?.phase === 'stopping' ? 'STOPPING' : inMission ? agent === 'claude' ? 'REASONING' : 'BUILDING' : modes[agent] === 'build' ? 'BUILDING' : modes[agent] === 'plan' ? 'PLANNING' : 'RESPONDING' : connected ? 'READY' : 'SIGN IN';
    const process = p.runtime?.processes.find(process => process.role === agent), message = current?.messages.filter(message => message.role === 'assistant').at(-1), response = message?.content;
    const effort = p.status.reasoning?.[agent] || 'auto', catalog = p.catalog?.[agent], invalidEffort = !!catalog && effort !== 'auto' && !effortChoices(catalog, p.status.models[agent]).includes(effort);
    return <section key={agent} className={`reference-panel agent-card ${agent} ${p.agent === agent ? 'selected' : ''} ${running ? 'processing' : ''}`} aria-label={`${name} agent status`}>
      <div className="agent-card-heading"><button className="agent-card-identity" aria-label={`Select ${name}`} onClick={() => p.select(agent)}><MinecraftWorker kind={agent} working={!!running && !waiting} /><div><h2>{name.toUpperCase()}</h2><span>{agent === 'claude' ? 'ARCHITECT · REASON · PLAN' : 'ENGINEER · BUILD · SHIP'}</span></div></button><span className="agent-card-state"><i />{phase}</span><details className="agent-menu"><summary aria-label={`${name} actions`}>⋮</summary><div onClick={event => event.currentTarget.closest('details')?.removeAttribute('open')}><button onClick={() => p.start(agent)}><PixelIcon name="plus" size={11} />New {name} session</button><button onClick={p.settings}><PixelIcon name="link" size={11} />{connected ? 'Manage connection' : 'Subscription sign-in'}</button><button onClick={p.check}><PixelIcon name="check" size={11} />Check connection</button></div></details></div>
      <div className="agent-card-body"><AgentPreferences agent={agent} catalog={catalog} model={p.status.models[agent]} reasoning={effort} disabled={p.preferencesBusy || !!running || !!p.mission} change={(model, effort) => p.changePreferences(agent, model, effort)} />
        <div className="agent-channel-meta"><span><i />{process ? `PID ${process.pid}` : connected ? 'SUBSCRIPTION CONNECTED' : 'SIGN IN REQUIRED'}</span><span>{p.contextCount ? `${p.contextCount} VAULT CONTEXT` : 'DIRECT CHANNEL'}</span></div>
        <div className="agent-response-preview" aria-live="polite" aria-busy={!!running}>{response ? <Markdown>{response}</Markdown> : <div className="agent-idle-message"><p>{running ? waiting ? 'Waiting for the Claude plan…' : `${name} is working on your prompt…` : current ? 'Your conversation is ready to continue.' : `Prompt ${name} right here. Choose a model, set the reasoning, then run.`}</p><span>{current?.title || 'YOUR NEXT IDEA STARTS HERE'}</span></div>}{running && <span className="processing-track" role="progressbar" aria-label={`${name} response in progress`} aria-valuetext={phase}><i /><i /><i /><i /><i /></span>}</div>
        <form className="agent-prompt-form" onSubmit={event => { event.preventDefault(); if (!running && !p.mission && !p.preferencesBusy && !invalidEffort) p.submit(agent, modes[agent]); }}><textarea aria-label={`${name} prompt`} placeholder={`Ask ${name} to think, plan, or build…`} rows={2} maxLength={20000} value={p.drafts[agent]} onChange={event => p.setDraft(agent, event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing) { event.preventDefault(); if (!running && !p.mission && !p.preferencesBusy && !invalidEffort) p.submit(agent, modes[agent]); } }} />
          <div><select aria-label={`${name} prompt mode`} value={modes[agent]} disabled={!!running} onChange={event => setModes(previous => ({ ...previous, [agent]: event.target.value as 'chat' | 'plan' | 'build' }))}><option value="chat">Chat</option><option value="plan">Plan · read project</option><option value="build">Build · edit project</option></select>{running ? <Button variant="danger" icon="stop" onClick={() => p.stop(agent)} aria-label={`Stop ${name}`}>STOP</Button> : <Button type="submit" variant={agent === 'claude' ? 'stone' : 'green'} icon="play" aria-label={`Run ${name} prompt`} disabled={!p.drafts[agent].trim() || p.preferencesBusy || invalidEffort || !!p.mission}>RUN {name.toUpperCase()}</Button>}</div>
        </form>
      </div><div className="agent-card-footer"><button aria-label={`Open ${name} conversation`} onClick={() => p.open(agent)}>FULL CONVERSATION ↗</button>{response && !running && !message?.error ? <button aria-label={`Save ${name} response to vault`} onClick={() => p.saveResponse(agent, response)}>SAVE TO VAULT ↗</button> : <span>{sessions.length} SAVED SESSIONS</span>}</div>
    </section>;
  })}</div>;
}
