import { useEffect, useState, type CSSProperties } from 'react';
import type { RuntimeEvent, RuntimeSnapshot } from '../types';

function Voxel({ x, y, size = 12, height = 15, color = 'mint', grid = false }: { x: number; y: number; size?: number; height?: number; color?: string; grid?: boolean }) {
  const s = size, h = height;
  return <g className={`voxel ${color}`} transform={`translate(${x} ${y})`}><polygon className="voxel-top" points={`0,${-s / 2} ${s},0 0,${s / 2} ${-s},0`} /><polygon className="voxel-left" points={`${-s},0 0,${s / 2} 0,${s / 2 + h} ${-s},${h}`} /><polygon className="voxel-right" points={`0,${s / 2} ${s},0 ${s},${h} 0,${s / 2 + h}`} />{grid && <g className="voxel-grid">{[.2, .4, .6, .8].map(r => <g key={r}><path d={`M${-s + s * r} ${s * r / 2}v${h}M${s * r} ${s / 2 - s * r / 2}v${h}`} /><path d={`M${-s} ${h * r} 0 ${s / 2 + h * r} ${s} ${h * r}`} /><path d={`M${-s + s * r} ${-s * r / 2} ${s * r} ${s / 2 - s * r / 2}M${-s * r} ${s / 2 - s * r / 2} ${s - s * r} ${-s * r / 2}`} /></g>)}</g>}</g>;
}
const paths = { claude: 'M8 130 C88 142 123 200 244 236', codex: 'M7 393 C78 399 156 373 252 318', vault: 'M633 157 C538 169 478 238 399 273', system: 'M328 535 C300 456 352 411 327 355', project: 'M328 535 C300 456 352 411 327 355' };
export function RuntimeCore({ runtime, events, connected, phase }: { runtime: RuntimeSnapshot | null; events: RuntimeEvent[]; connected: boolean; phase?: string }) {
  const [reduced, setReduced] = useState(() => window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(() => { const media = window.matchMedia('(prefers-reduced-motion: reduce)'); const change = () => setReduced(media.matches); media.addEventListener('change', change); return () => media.removeEventListener('change', change); }, []);
  const packets = events.filter(e => e.type !== 'telemetry' && Date.now() - e.time < 5000).slice(0, 9);
  const ring = Array.from({ length: 42 }, (_, i) => { const angle = i / 42 * Math.PI * 2; return { x: 320 + Math.cos(angle) * 212, y: 305 + Math.sin(angle) * 80, i }; });
  const latest = events.find(event => event.type !== 'telemetry' && event.text);
  return <section className={`system-core ${connected ? 'online' : 'offline'} ${runtime?.activeJobs || phase ? 'processing' : ''}`} aria-label="Live system core" style={{ '--core-load': runtime?.cpu == null ? .35 : .25 + runtime.cpu / 140 } as CSSProperties}>
    <div className="core-title"><span>LOCAL ORCHESTRATION</span><h1>APHELION</h1><p>UNIFY › REASON › BUILD › REMEMBER</p></div>
    <svg className="core-scene" viewBox="0 65 640 440" fill="none" aria-hidden="true"><defs><radialGradient id="core-light"><stop stopColor="#1fe9b0" stopOpacity=".23" /><stop offset="1" stopColor="#1fe9b0" stopOpacity="0" /></radialGradient><linearGradient id="beam-light" x1="0" y1="0" x2="1" y2="0"><stop stopColor="#00ffb7" stopOpacity="0" /><stop offset=".5" stopColor="#5fffd4" stopOpacity=".2" /><stop offset="1" stopColor="#00ffb7" stopOpacity="0" /></linearGradient><filter id="core-bloom"><feGaussianBlur stdDeviation="5" /></filter><pattern id="core-floor" width="36" height="22" patternUnits="userSpaceOnUse" patternTransform="rotate(0)"><path d="M0 11 18 0 36 11 18 22Z" stroke="#3bcaba" strokeOpacity=".08" /></pattern></defs>
      <ellipse cx="320" cy="317" rx="311" ry="150" fill="url(#core-light)" /><path d="M2 397 320 224 638 397 320 550Z" fill="url(#core-floor)" /><rect className="core-beam" x="268" y="0" width="105" height="420" fill="url(#beam-light)" />
      <g className="core-connection-paths">{Object.entries(paths).map(([source, path]) => <path key={source} className={source} d={path} />)}</g>
      <g className="core-orbits"><ellipse cx="320" cy="321" rx="282" ry="109" /><ellipse cx="320" cy="323" rx="247" ry="93" /><ellipse className="core-outer-pulse" cx="320" cy="309" rx="273" ry="118" /></g>
      {ring.filter(block => block.y < 306).map(block => <Voxel key={block.i} x={block.x} y={block.y} size={11} height={19} color={block.i % 5 ? 'stone' : 'mint'} />)}
      <g className="core-floor-blocks">{Array.from({ length: 34 }, (_, i) => { const angle = i * 2.39996, radius = 65 + (i * 17 % 125); return <Voxel key={i} x={320 + Math.cos(angle) * radius} y={318 + Math.sin(angle) * radius * .37} size={8 + i % 5} height={12 + i % 3 * 9} color={i % 4 ? 'dark' : 'mint'} />; })}</g>
      <g className="core-reactor"><path className="core-cage" d="M320 142 416 190V322L320 372 224 322V190Z M224 190 320 239 416 190M320 239V372" /><Voxel x={320} y={206} size={68} height={91} color="reactor" grid /><Voxel x={320} y={140} size={17} height={27} color="reactor" grid /><path className="core-stem" d="M320 169V188M252 235 224 220M388 235 416 220" /><Voxel x={250} y={278} size={12} height={28} color="mint" /><Voxel x={390} y={277} size={12} height={28} color="mint" /></g>
      <g className="core-ring-energy"><ellipse cx="320" cy="298" rx="169" ry="66" filter="url(#core-bloom)" /><ellipse cx="320" cy="298" rx="169" ry="66" /><ellipse cx="320" cy="310" rx="171" ry="68" /><path d="M151 298v13M489 298v13M320 233v11M320 365v12" /></g>
      {ring.filter(block => block.y >= 306).map(block => <Voxel key={block.i} x={block.x} y={block.y} size={11} height={19} color={block.i % 5 ? 'stone' : 'mint'} />)}
      <g className="core-satellites"><Voxel x={82} y={379} size={13} height={18} color="cyan" /><Voxel x={553} y={198} size={12} height={17} color="purple" /><Voxel x={147} y={177} size={10} height={14} color="amber" /><Voxel x={456} y={427} size={13} height={18} color="mint" /></g>
      {!reduced && <g className="core-live-packets">{packets.map(event => <g key={event.id} className={`data-packet ${event.source}`}><circle r="5"><animateMotion path={paths[event.source]} dur="1.2s" fill="freeze" /><animate attributeName="opacity" values="1;1;0" keyTimes="0;.8;1" dur="1.5s" fill="freeze" /></circle><circle r="2" fill="#e5fff8"><animateMotion path={paths[event.source]} dur="1.2s" fill="freeze" /><animate attributeName="opacity" values="1;1;0" keyTimes="0;.8;1" dur="1.5s" fill="freeze" /></circle></g>)}</g>}
      <g className="core-route-labels"><text x="44" y="217">CLAUDE / PLAN</text><text x="28" y="433">CODEX / BUILD</text><text x="477" y="112">VAULT / CONTEXT</text><text x="235" y="463">ALL CONTEXT. HIGHER HORIZONS.</text></g>
    </svg>
    <div className="core-live-state"><span className={`core-heartbeat ${connected ? '' : 'disconnected'}`} /><strong>{connected ? phase ? `MISSION / ${phase.toUpperCase()}` : runtime?.activeJobs ? `${runtime.activeJobs} ACTIVE JOB${runtime.activeJobs === 1 ? '' : 'S'}` : 'SYSTEM ONLINE' : 'CONNECTING LOCAL ENGINE'}</strong><span>{latest?.text || (connected ? 'Standing by for your next mission.' : 'Waiting for live telemetry.')}</span></div>
  </section>;
}
