import type { RuntimeSnapshot } from '../types';

export function bytes(value: number): string { if (value < 1024) return `${value} B`; if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`; return `${(value / 1024 / 1024).toFixed(1)} MB`; }
export function SystemStrip({ runtime, history, connected }: { runtime: RuntimeSnapshot | null; history: RuntimeSnapshot[]; connected: boolean }) {
  const samples = history.filter(sample => sample.cpu !== null).slice(-30);
  const cpu = runtime?.cpu, memory = runtime?.memory;
  const processes = runtime?.processes || [];
  const line = samples.map((sample, i) => `${samples.length > 1 ? i / (samples.length - 1) * 215 : 0},${42 - Math.min(100, sample.cpu || 0) / 100 * 36}`).join(' ');
  return <section className="live-system-strip" aria-label="Live system telemetry"><div className="reference-panel topology-panel"><div className="telemetry-label">SYSTEM TOPOLOGY<span className={connected ? 'live' : 'offline'}>{connected ? 'LIVE' : 'CONNECTING'}</span></div><div className="topology-values"><span><strong>{runtime?.activeJobs ?? '—'}</strong> ACTIVE JOBS</span><span><strong>{runtime?.network.clients ?? '—'}</strong> CLIENTS</span><span><strong>{processes.length || (runtime ? 0 : '—')}</strong> PROCESSES</span></div><div className="network-stat"><i className={runtime?.network.online ? 'online' : ''} /><span>NETWORK {runtime ? runtime.network.online ? 'ONLINE' : 'OFFLINE' : 'WAITING'}</span>{runtime && <span>↓ {bytes(runtime.network.received)} / ↑ {bytes(runtime.network.sent)}</span>}</div></div>
    <div className="reference-panel resources-panel"><div className="resource-cells"><div className="telemetry-label">SYSTEM RESOURCES</div><div className="resource-values"><div><span>CPU<strong>{cpu == null ? '—' : `${cpu.toFixed(0)}%`}</strong></span><i><b style={{ width: `${cpu == null ? 0 : Math.max(0, Math.min(100, cpu))}%` }} /></i></div><div><span>MEMORY<strong>{memory ? `${memory.percent.toFixed(0)}%` : '—'}</strong></span><i><b style={{ width: `${memory ? Math.max(0, Math.min(100, memory.percent)) : 0}%` }} /></i></div></div></div><div className="activity-sparkline"><span>CPU HISTORY / LIVE</span><svg viewBox="0 0 215 46" aria-label="Actual CPU history"><path d="M0 10h215M0 25h215M0 40h215M30 0v46M70 0v46M110 0v46M150 0v46M190 0v46" stroke="#294852" strokeWidth=".7" />{line && <polyline points={line} fill="none" stroke="#52e8c1" strokeWidth="1.5" />}</svg></div></div>
    <div className="reference-panel processes-panel"><div className="telemetry-label">ACTIVE PROCESSES<span>{runtime?.time ? new Date(runtime.time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }) : 'WAITING'}</span></div><div className="process-list">{processes.length ? processes.map(process => <span className={process.role} key={`${process.pid}-${process.name}`} title={`PID ${process.pid} · ${process.role}`}><i />{process.name}<small>{process.pid}</small></span>) : <span className="process-wait">{runtime ? 'No agent processes running.' : 'Waiting for engine processes.'}</span>}</div></div>
  </section>;
}
