import { _electron as electron } from 'playwright';
import { mkdtemp, readFile, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';

const userData = await mkdtemp(join(tmpdir(), 'aphelion-desktop-test-'));
const launchEnv = { ...process.env, APHELION_TEST_HOME: userData };
delete launchEnv.ELECTRON_RUN_AS_NODE;
delete launchEnv.APHELION_DEV_URL;
const executablePath = process.argv[2];
const desktop = await electron.launch({ ...(executablePath ? { executablePath: resolve(executablePath) } : {}), args: executablePath ? [] : [resolve('.')], env: launchEnv, timeout: 30000 });
try {
  const page = await desktop.firstWindow();
  await page.getByRole('textbox', { name: 'Your prompt', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Graph', exact: true }).waitFor();
  const fontLoaded = await page.evaluate(async () => { const fonts = await document.fonts.load('13px Monocraft'); return fonts.length > 0 && fonts.every(font => font.status === 'loaded'); });
  assert.equal(fontLoaded, true, 'The packaged pixel font must load from local assets.');
  const headingFont = await page.evaluate(async () => { const fonts = await document.fonts.load('700 28px "Pixelify Sans"'); return fonts.length > 0 && fonts.every(font => font.status === 'loaded'); });
  assert.equal(headingFont, true, 'The heading pixel font must load from local assets.');
  const status = await page.evaluate(() => window.aphelion.status());
  assert.equal(status.desktop, true);
  assert.equal('keys' in status, false);
  assert.equal('voiceId' in status, false);
  assert.ok(['subscription', 'missing', 'signed-out', 'api-key'].includes(status.auth.claude.mode));
  await assert.rejects(page.evaluate(() => window.aphelion.configure({ keys: { claude: 'forbidden-key' } })));
  assert.equal(await page.locator('input[type=password]').count(), 0);
  assert.equal(await page.locator('.sidebar').count(), 0);
  const notes = await page.evaluate(() => window.aphelion.listNotes());
  assert.equal(notes.some(note => note.path === 'Welcome.md'), true);
  const graph = await page.evaluate(() => window.aphelion.vaultGraph());
  assert.ok(graph.nodes.length >= 4);
  assert.ok(graph.edges.some(edge => edge.from === 'Project Memory.md' && edge.to === 'Architecture.md'));
  const runtime = await page.evaluate(() => window.aphelion.runtime());
  assert.ok(runtime.time > 0 && runtime.memory.total > 0);
  assert.ok(runtime.processes.some(process => process.role === 'system' && process.pid > 0));
  assert.equal(runtime.obsidian.watching, true);
  await writeFile(join(userData, 'vault', 'External edit.md'), '# External disk edit\n\n[[Project Memory]]\n');
  await page.waitForFunction(async () => (await window.aphelion.listNotes()).some(note => note.path === 'External edit.md'));
  const project = await page.evaluate(() => window.aphelion.createProject('desktop-proof'));
  await mkdir(join(project.path, 'src'));
  await writeFile(join(project.path, 'src', 'proof.mjs'), 'export const proof = "APHELION_LOCAL_PROCESS_OK";\n');
  await writeFile(join(project.path, 'package.json'), JSON.stringify({ name: 'desktop-proof', scripts: { test: 'node --test src/proof.mjs' } }));
  const files = await page.evaluate(() => window.aphelion.listProjectFiles());
  assert.ok(files.some(file => file.name === 'src' && file.kind === 'directory'));
  const command = await page.evaluate(() => window.aphelion.runProjectCommand('test'));
  assert.equal(command.code, 0, command.output);
  assert.ok(command.output.includes('proof.mjs'));
  await assert.rejects(page.evaluate(() => window.aphelion.readNote('../credentials.md')));
  const preferences = await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences());
  assert.equal(preferences.contextIsolation, true);
  assert.equal(preferences.nodeIntegration, false);
  assert.equal(preferences.sandbox, true);
  await page.getByRole('button', { name: 'Vault', exact: true }).click();
  await page.getByRole('textbox', { name: 'Note content' }).waitFor();
  await page.getByRole('button', { name: 'Home', exact: true }).click();
  await page.evaluate(async () => { await Promise.all(document.getAnimations().filter(animation => animation.effect?.getComputedTiming().iterations !== Infinity).map(animation => animation.finished.catch(() => {}))); });
  await mkdir('test-results', { recursive: true });
  await page.screenshot({ path: 'test-results/aphelion-desktop.png' });
  console.log('PASS: desktop launch, foreground vault and disk refresh, local pixel fonts, real telemetry, project files and npm process, sandboxed bridge, subscription-only settings, no sidebar, and vault confinement.');
} finally { await desktop.close(); }
