export type Agent = 'claude' | 'codex';
export type Page = 'home' | 'chat' | 'vault' | 'workflows' | 'voice' | 'settings';
export type Message = { id: string; role: 'user' | 'assistant'; content: string; demo?: boolean; error?: boolean; pending?: boolean };
export type Session = { id: string; agent: Agent; title: string; created: string; messages: Message[] };
export type Workspace = { version: 1; sessions: Session[]; active: Record<Agent, string | null>; name: string; sound: boolean };
export type Note = { path: string; title: string; modified: string; content?: string; revision?: string; create?: boolean };
export type VaultGraph = { nodes: { id: string; path: string; title: string; tags: string[]; excerpt: string; modified: string }[]; edges: { from: string; to: string }[]; total: number; truncated: boolean };
export type Connection = { installed: boolean; signedIn: boolean; mode: 'subscription' | 'signed-out' | 'api-key' | 'missing'; detail: string };
export type Status = { desktop: boolean; connected: Record<Agent, boolean>; auth: Record<Agent, Connection>; models: Record<Agent, string>; reasoning?: Record<Agent, string>; vaultPath: string; repo: string };
export type ModelOption = { id: string; name: string; description: string; efforts: string[]; defaultEffort?: string; isDefault?: boolean; resolved?: string };
export type ModelCatalog = Record<Agent, { models: ModelOption[]; error?: string }>;
export type ChatRequest = { agent: Agent; messages: Pick<Message, 'role' | 'content'>[]; requestId: string; mode?: 'chat' | 'plan' | 'build'; contextPaths?: string[] };
export type ChatResult = { text: string; demo: boolean; usage: { input: number; output: number } };
export type SettingsInput = { models?: Record<Agent, string>; reasoning?: Record<Agent, string>; repo?: string };
export type ProjectInfo = { path: string; name: string; branch: string | null; dirty: boolean };
export type ProjectFile = { path: string; name: string; kind: 'file' | 'directory' };
export type AutomationInfo = { id: string; name: string; status: 'idle' | 'running'; detail: string };
export type ObsidianInfo = { installed: boolean; running: boolean; vaultPath: string; watching: boolean; indexedAt: number; noteCount: number; detail: string };
export type RuntimeSnapshot = { time: number; cpu: number | null; memory: { used: number; total: number; percent: number }; network: { online: boolean; clients: number; received: number; sent: number }; processes: { pid: number; name: string; role: string }[]; activeJobs: number; project: ProjectInfo | null; obsidian: ObsidianInfo; heartbeat: number };
export type RuntimeEvent = { id: string; time: number; type: 'telemetry' | 'activity' | 'terminal' | 'vault' | 'mission'; source: 'system' | 'claude' | 'codex' | 'vault' | 'project'; text?: string; requestId?: string; phase?: string; data?: unknown };
export type MissionResult = { plan: string; build: string; project: ProjectInfo | null; receiptPath: string };
export interface AphelionBridge {
  status(): Promise<Status>;
  modelCatalog(): Promise<ModelCatalog>;
  configure(input: SettingsInput): Promise<Status>;
  login(agent: Agent): Promise<Status>;
  runtime(): Promise<RuntimeSnapshot>;
  onRuntimeEvent(handler: (event: RuntimeEvent) => void): () => void;
  mission(request: { task: string; requestId: string; contextPaths?: string[] }): Promise<MissionResult>;
  project(): Promise<ProjectInfo | null>;
  selectProject(): Promise<ProjectInfo | null>;
  createProject(name: string): Promise<ProjectInfo>;
  listProjectFiles(path?: string): Promise<ProjectFile[]>;
  readProjectFile(path: string): Promise<{ path: string; content: string }>;
  runProjectCommand(command: string): Promise<{ code: number; output: string }>;
  automations(): Promise<AutomationInfo[]>;
  runAutomation(id: string): Promise<{ code: number; output: string }>;
  obsidian(): Promise<ObsidianInfo>;
  openObsidian(path?: string): Promise<ObsidianInfo>;
  chat(request: ChatRequest): Promise<ChatResult>;
  cancel(requestId: string): Promise<void>;
  onDelta(handler: (event: { requestId: string; delta: string }) => void): () => void;
  selectVault(): Promise<Status | null>;
  listNotes(): Promise<Note[]>;
  vaultGraph(): Promise<VaultGraph>;
  readNote(path: string): Promise<Note>;
  saveNote(note: Note & { content: string }): Promise<Note>;
  openExternal(url: string): Promise<void>;
  windowAction(action: 'minimize' | 'maximize' | 'close'): Promise<void>;
}
declare global { interface Window { aphelion?: AphelionBridge } }
